# Generated by Django 4.2.15 on 2024-10-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'permissions': [('create_eventos', 'Puede crear eventos'), ('edit_eventos', 'Puede editar eventos'), ('delete_eventos', 'Puede eliminar eventos'), ('view_eventos', 'Puede ver eventos')]},
        ),
    ]
