# Generated by Django 4.2.15 on 2024-10-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='creador',
        ),
    ]
